from typing import Self, final

import numpy as np
import numpy.typing as npt
from typing_extensions import Buffer

__all__ = [
    "__version__",
    "lustro_api_version",
    "hash256",
    "hash128",
    "hash256_many",
    "hash128_many",
    "hash256_many_var",
    "hash128_many_var",
    "LustroPrng",
    "LustroPrngBatch",
    "LustroXof",
    "LustroXofBatch",
]

__version__: str

def lustro_api_version() -> int: ...
def hash256(data: bytes) -> bytes: ...
def hash128(data: bytes) -> bytes: ...
def hash256_many(data: npt.NDArray[np.uint8]) -> npt.NDArray[np.uint8]: ...
def hash128_many(data: npt.NDArray[np.uint8]) -> npt.NDArray[np.uint8]: ...
def hash256_many_var(messages: list[bytes]) -> npt.NDArray[np.uint8]: ...
def hash128_many_var(messages: list[bytes]) -> npt.NDArray[np.uint8]: ...

@final
class LustroPrng:
    def __new__(cls, seed: bytes, stream_id: int = 0) -> Self: ...
    def next_u64(self) -> int: ...
    def next_u128(self) -> int: ...
    def next_block(self) -> bytes: ...
    def fill(self, size: int) -> bytes: ...
    def fill_into(self, buf: Buffer) -> None: ...
    def copy(self) -> Self: ...
    def __copy__(self) -> Self: ...
    def __deepcopy__(self, _memo: object) -> Self: ...
    def fork(self, id: int) -> Self: ...
    @staticmethod
    def derive_path(seed: bytes, path: list[int]) -> LustroPrng: ...
    def export_snapshot(self) -> bytes: ...
    @staticmethod
    def import_snapshot(bytes: bytes) -> LustroPrng: ...

@final
class LustroPrngBatch:
    def __new__(cls, seed: bytes, stream_ids: list[int]) -> Self: ...
    @staticmethod
    def new_range(seed: bytes, first_stream_id: int, count: int) -> LustroPrngBatch: ...
    def __len__(self) -> int: ...
    def len(self) -> int: ...
    def is_empty(self) -> bool: ...
    def copy(self) -> Self: ...
    def __copy__(self) -> Self: ...
    def __deepcopy__(self, _memo: object) -> Self: ...
    def release_buffer(self) -> None: ...
    def suggested_steps(self) -> int: ...
    def fill_blocks(self, out: npt.NDArray[np.uint64], steps: int) -> None: ...
    def fork(self, ids: list[int]) -> Self: ...
    def fork_many(self, ids: list[int]) -> Self: ...
    def fork_range(self, first: int) -> Self: ...
    @staticmethod
    def derive_path(seed: bytes, roots: list[int], path: list[int]) -> LustroPrngBatch: ...
    def export_snapshot(self) -> bytes: ...
    @staticmethod
    def import_snapshot(bytes: bytes) -> LustroPrngBatch: ...

@final
class LustroXof:
    def __new__(cls, message: bytes) -> Self: ...
    def next_u64(self) -> int: ...
    def next_u128(self) -> int: ...
    def next_block(self) -> bytes: ...
    def fill(self, size: int) -> bytes: ...
    def fill_into(self, buf: Buffer) -> None: ...
    def copy(self) -> Self: ...
    def __copy__(self) -> Self: ...
    def __deepcopy__(self, _memo: object) -> Self: ...
    def fork(self, id: int) -> Self: ...
    @staticmethod
    def derive_path(message: bytes, path: list[int]) -> LustroXof: ...
    def export_snapshot(self) -> bytes: ...
    @staticmethod
    def import_snapshot(bytes: bytes) -> LustroXof: ...

@final
class LustroXofBatch:
    def __new__(cls, messages: list[bytes]) -> Self: ...
    def __len__(self) -> int: ...
    def len(self) -> int: ...
    def is_empty(self) -> bool: ...
    def copy(self) -> Self: ...
    def __copy__(self) -> Self: ...
    def __deepcopy__(self, _memo: object) -> Self: ...
    def release_buffer(self) -> None: ...
    def suggested_steps(self) -> int: ...
    def fill_blocks(self, out: npt.NDArray[np.uint64], steps: int) -> None: ...
    def fork(self, ids: list[int]) -> Self: ...
    def fork_many(self, ids: list[int]) -> Self: ...
    def fork_range(self, first: int) -> Self: ...
    @staticmethod
    def derive_path(messages: list[bytes], path: list[int]) -> LustroXofBatch: ...
    def export_snapshot(self) -> bytes: ...
    @staticmethod
    def import_snapshot(bytes: bytes) -> LustroXofBatch: ...